services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["bash", "run.sh"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    command: ["streamlit", "run", "main.py"]